image: alpine:edge

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - apk update
    - apk add hugo
    - cd exampleSite && hugo --config .config.ci.toml
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  script:
    - apk update
    - apk add hugo
    - cd exampleSite && hugo --config .config.ci.toml
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
