image: alpine:edge

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_MIN_VERSION: "0.65.0"

test-latest:
  script:
    - apk update
    - apk add hugo
    - cd exampleSite && hugo --config .config.ci.toml
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

test-minversion:
  script:
    # Hugo 0.64.0 is not available on Alpine packages, so revert to the good old method
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_MIN_VERSION}/hugo_${HUGO_MIN_VERSION}_Linux-64bit.tar.gz
    - mkdir -p bin
    - cd bin
    - tar -xzf $CI_PROJECT_DIR/hugo_${HUGO_MIN_VERSION}_Linux-64bit.tar.gz
    - export PATH=$PATH:${CI_PROJECT_DIR}/bin
    - cd ${CI_PROJECT_DIR}/exampleSite && hugo --config .config.ci.toml
  except:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  script:
    - apk update
    - apk add hugo
    - cd exampleSite && hugo --config .config.ci.toml
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
