title = "Hugo Split Gallery theme sample site"
copyright = "Theme licensed under the GPLv3 license; photos are &copy; Thomas Muguet"
baseURL = "https://tmuguet.gitlab.io/hugo-split-gallery/next/"
languageCode = "en-us"
theme = "hugo-split-gallery"
themesDir = "../.."
publishDir = "../public/next"  # GitLab expects public folder at root

DefaultContentLanguage = "en"

[taxonomies]
  location = "locations"
  season = "seasons"

[params]
  robots = "index, follow"
  favicon = ""
  siteLogo = ""
  description = "Photo gallery inspired by Hugo Split Theme"
  images = ["DSCF0348.jpg"]
  includeOriginalImage = false
  largeImageSize = "2000x"
  footnote = "Fork me on <a href='https://gitlab.com/tmuguet/hugo-split-gallery'>GitLab</a>!"
  galleryLoop = true
  galleryButtons = ["zoom", "fullScreen", "slideShow", "close"]

  [params.taxonomies]
    [params.taxonomies.locations]
      icon = "location-arrow"
    [params.taxonomies.seasons]
      icon = "calendar"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About this theme"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    name = "Getting started"
    pre = "<i class='fa fa-road'></i>"
    url = "/getting-started/"
    weight = -100

  [[menu.main]]
    name = "See stable version"
    pre = "<i class='fa fa-floppy-o'></i>"
    url = "https://tmuguet.gitlab.io/hugo-split-gallery/"

